blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('cars.urls', namespace='cars')),
                  path('', include('blog.urls', namespace='blogs')),
                  path('', include('contacts.urls', namespace='contacts')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path

from contacts.apps import ContactsConfig
from contacts.views import (ContactListView, ContactDetailView, ContactCreateView, ContactUpdateView, ContactDeleteView)

app_name = ContactsConfig.name

urlpatterns = [
    path('contacts/', ContactListView.as_view(), name='contact_list'),
    path('contacts/<int:pk>/', ContactDetailView.as_view(), name='contact_detail'),
    path('contacts/create', ContactCreateView.as_view(), name='contact_create'),
    path('contacts/<int:pk>/update/', ContactUpdateView.as_view(), name='contact_update'),
    path('contacts/<int:pk>/delete/', ContactDeleteView.as_view(), name='contact_delete'),

]

contacts/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Contact(models.Model):
    objects = None
    name = models.CharField(max_length=200, verbose_name='Имя')
    email = models.EmailField(verbose_name='почта', unique=True)
    surname = models.CharField(verbose_name='Фамилия')
    contact_img = models.ImageField(upload_to='cars/contact_img', verbose_name='Изображение', blank=True, null=True)
    birthday = models.DateField(auto_now_add=True, verbose_name='Дата рождения', blank=True, null=True)
    slug = models.CharField(max_length=100, verbose_name='slug', blank=True, null=True)

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return f'{self.name} {self.surname} {self.email} {self.birthday}'

contacts/views.py
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from contacts.models import Contact


class ContactListView(ListView):
    model = Contact


class ContactDetailView(DetailView):
    model = Contact


class ContactCreateView(CreateView):
    model = Contact
    fields = ("name", "surname", "email", "contact_img")
    success_url = reverse_lazy('contacts:contact_list')

    def form_valid(self, form):
        if form.is_valid():
            contact_new = form.save()
            contact_new.slug = slugify(contact_new.name)
            contact_new.save()

        return super().form_valid(form)


class ContactUpdateView(UpdateView):
    model = Contact
    fields = ("name", "surname", "email", "contact_img")
    success_url = reverse_lazy('contacts:contact_list')

    def get_success_url(self):
        return reverse('contacts:contact_detail', args=[self.kwargs.get('pk')])


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy('contacts:contact_list')

contacts/templates/contacts/contact_confirm_delete.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                     <p class="card-text">Хотите удалить {{ object.name }} {{ object.surname }}</p>
                    <button type="submit" class="btn btn-primary" style="margin-bottom: 10px;">
                       Удалить
                    </button>
                    <button type="submit" class="btn btn-primary">
                    <a class="btn btn-primary" href="{% url 'contacts:contact_list' %}" role="button">
                        Отмена</a>
                   </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_detail.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.contact_img | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Имя: {{ object.name }}</p>
                        <p class="card-text">Фамилия: {{ object.surname }}</p>
                        <p class="card-text">Почта: {{ object.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" style="margin-bottom: 10px;"
                                   href="{% url 'contacts:contact_list' %}"
                                   role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_form.html
{% extends 'cars/car.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button><br>
                    <a class="btn btn-primary"  href="{% url 'contacts:contact_list' %}"
                    role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_list.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <p>
            <a class="btn btn-primary" href="{% url 'contacts:contact_create' %}" role="button">Добавить контакт</a>
        </p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for contact in object_list %}
            <div class="col-12">
                <div class="card shadow-sm">
                    <img src="{{ contact.contact_img | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Имя: {{ contact.name }}</p>
                        <p class="card-text">Фамилия: {{ contact.surname }}</p>
                        <p class="card-text">Почта: {{ contact.email }}</p>
                        <div>
                            <div class="btn-group" style="margin-bottom: 10px;">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'contacts:contact_detail' contact.pk %}" role="button">
                                    Подробнее</a>
                            </div>
                            <div class="btn-group ">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'contacts:contact_update' contact.pk %}" role="button">
                                    Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'contacts:contact_delete' contact.pk %}"
                                   role="button">
                                    Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}