blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('cars.urls', namespace='cars')),
                  path('', include('blog.urls', namespace='blogs')),
                  path('', include('contacts.urls', namespace='contacts')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    objects = None
    title = models.CharField(max_length=100, verbose_name='заголовок')
    description = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='cars/image', blank=True, null=True, verbose_name='Изображение')
    public = models.IntegerField(verbose_name='признак публикации', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    slug = models.CharField(max_length=100, verbose_name='slug', blank=True, null=True)

    view_counter = models.PositiveIntegerField(
        verbose_name='Счетчик просмотров',
        help_text='Укажите колличество просмотров',
        default=0
    )

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

    def __str__(self):
        return f'{self.title} {self.description} {self.public} {self.created_at}'

blog/views.py
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ("title", "description", "image")
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            blog_new = form.save()
            blog_new.slug = slugify(blog_new.title)
            blog_new.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("title", "description", "image")
    success_url = reverse_lazy('blog:blog_list')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                     <p class="card-text">Хотите удалить {{ object.title }}</p>
                    <button type="submit" class="btn btn-primary" style="margin-bottom: 10px;">
                       Удалить
                    </button>
                    <button type="submit" class="btn btn-primary">
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">
                        Отмена</a>
                   </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Наименование: {{ object.title }}</p>
                        <p class="card-text">pfvtnrf:<br> {{ object.description | truncatechars:99 }}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" style="margin-bottom: 10px;"
                                   href="{% url 'blog:blog_list' %}"
                                   role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'cars/car.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button><br>
                    <a class="btn btn-primary"  href="{% url 'blog:blog_list' %}"
                    role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
<p>
        <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Добавить заметку</a>
    </p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for blog in object_list %}
            <div class="col-12">
                <div class="card shadow-sm">
                    <img src="{{ blog.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ blog.title }}</p>
                        <p class="card-text">Описание: {{ blog.description | truncatechars:99 }}</p>

                        <div>
                            <div class="btn-group" style="margin-bottom: 10px;">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'blog:blog_detail' blog.pk %}" role="button">
                                    Подробнее</a>
                            </div>
                            <div class="btn-group ">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'blog:blog_update' blog.pk %}" role="button">
                                    Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'blog:blog_delete' blog.pk %}" role="button">
                                    Удалить</a>
                            </div>
                        </div>
                        <p class="card-text">Просмотров: {{ blog.view_counter }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}