blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

cars/urls.py
from django.urls import path

from cars.apps import CarsConfig
from cars.views import (CarListView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView)

app_name = CarsConfig.name

urlpatterns = [
    path('', CarListView.as_view(), name='product_list'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='product_detail'),
    path('cars/create', CarCreateView.as_view(), name='product_create'),
    path('cars/<int:pk>/update/', CarUpdateView.as_view(), name='product_update'),
    path('cars/<int:pk>/delete/', CarDeleteView.as_view(), name='product_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('cars.urls', namespace='cars')),
                  path('', include('blog.urls', namespace='blogs')),
                  path('', include('contacts.urls', namespace='contacts')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from django.db import models


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    photo = models.ImageField(upload_to='cars/photo', blank=True, null=True, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория',
                                 related_name='products')
    price = models.IntegerField(verbose_name='Цена за покупку', blank=True,
                                null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    view_counter = models.PositiveIntegerField(
        verbose_name='Счетчик просмотров',
        help_text='Укажите колличество просмотров',
        default=0
    )

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name} {self.description} {self.category} {self.price}'


class Version(models.Model):
    objects = None
    product = models.ForeignKey(Product, related_name='versions', on_delete=models.CASCADE, null=True, blank=True,
                                verbose_name='Версия машины', )
    name = models.TextField(verbose_name="название версии")
    number = models.IntegerField(verbose_name="номер версии", null=True, blank=True)
    sign = models.BooleanField(default=True, verbose_name='признак текущей версии')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return f'{self.name}'

cars/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from cars.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class CarForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ("view_counter",)
        # fields = "__all__"

    def clean_name(self):
        name_p = self.cleaned_data['name']
        if name_p in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']:
            raise ValidationError('Запрещенные слова')
        return name_p

    def clean_description(self):
        descr_p = self.cleaned_data['description']
        if descr_p in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']:
            raise ValidationError('Запрещенные слова')
        return descr_p


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

cars/views.py
from django.forms import inlineformset_factory
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from cars.forms import CarForm, VersionForm
from cars.models import Product, Version


class CarListView(ListView):
    model = Product

    # def get_queryset(self, *args, **kwargs):
    #     queryset = super().get_queryset(*args, **kwargs)
    #     queryset = queryset.filter(is_active=True)
    #     return queryset


class CarDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class CarCreateView(CreateView):
    model = Product
    form_class = CarForm
    success_url = reverse_lazy('cars:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        CarFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data["formset"] = CarFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = CarFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class CarUpdateView(UpdateView):
    model = Product
    form_class = CarForm
    success_url = reverse_lazy('cars:product_list')

    def get_success_url(self):
        return reverse('cars:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        CarFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data["formset"] = CarFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = CarFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class CarDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('cars:product_list')

cars/templates/cars/car.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AZhoff</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'cars/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">AZhoff</h1>
    <p class="lead">Идеальный магазин авто</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    {% include 'cars/includes/inc_footer.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
></script>
</body>
</html>

cars/templates/cars/product_confirm_delete.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <img src="{{ object.photo | media_filter }}">
                     <p class="card-text">Хотите удалить {{ object.name }}</p>
                    <button type="submit" class="btn btn-primary" style="margin-bottom: 10px;">
                       Удалить
                    </button>
                    <button type="submit" class="btn btn-primary">
                    <a class="btn btn-primary" href="{% url 'cars:product_list' %}" role="button">
                        Отмена</a>
                   </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

cars/templates/cars/product_detail.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.photo | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Наименование: {{ object.name }}</p>
                        <p class="card-text">Описание: {{ object.description | truncatechars:99 }}</p>
                        <p class="card-text">Цена: {{ object.price }}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'cars:product_list' %}" role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

cars/templates/cars/product_form.html
{% extends 'cars/car.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary" style="margin-bottom: 10px;">

                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}

                </button>

                <a class="btn btn-primary" href="{% url 'cars:product_list' %}"
                   role="button">Отмена</a>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <p class="card-text">Версионность авто</p>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</div>


{% endblock %}

cars/templates/cars/product_list.html
{% extends 'cars/car.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <p>
            <a class="btn btn-primary" href="{% url 'cars:product_create' %}" role="button">Добавить авто</a>
        </p>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for car in object_list %}
            <div class="col-4">
                <div class="card shadow-sm">
                    <img src="{{ car.photo | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ car.name }}</p>
                        <p class="card-text">Описание: {{ car.description | truncatechars:99 }}</p>

                        <div>
                            <div class="btn-group" style="margin-bottom: 10px;">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'cars:product_detail' car.pk %}" role="button">
                                    Подробнее</a>
                            </div>
                            <div class="btn-group ">
                                <a class="btn btn-primary" style="margin-right: 10px;"
                                   href="{% url 'cars:product_update' car.pk %}" role="button">
                                    Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'cars:product_delete' car.pk %}" role="button">
                                    Удалить</a>
                            </div>
                        </div>
                        {% for version in car.versions.all %}
                        {% if version.sign %}
                        <p class="card-text">Версия: {{ version.number }}. Название: {{ version.name }}</p>
                        {% endif %}
                        {% endfor %}

                        <p class="card-text">Просмотров: {{ car.view_counter }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}